#pragma once


// コンパイルが通れば成功
#define ID08_NO_COMPILE_ERROR_CHECK
#define ID34_NO_COMPILE_ERROR_CHECK
#define ID46_NO_COMPILE_ERROR_CHECK
// コンパイルが通らなければ成功
//#define ID15_COMPILE_ERROR_CHECK
//#define ID22_COMPILE_ERROR_CHECK
//#define ID28_COMPILE_ERROR_CHECK
//#define ID40_COMPILE_ERROR_CHECK




// コンパイルが通らなければ成功
//#define ID02_USER_COMPILE_ERROR_CHECK
//#define ID17_USER_COMPILE_ERROR_CHECK
//#define ID19_USER_COMPILE_ERROR_CHECK
