#pragma once




// コンパイルが通れば成功
#define ID12_HASH_NO_COMPILE_ERROR_CHECK
#define ID34_HASH_NO_COMPILE_ERROR_CHECK

// コンパイルが通らなければ成功
//#define ID00_HASH_COMPILE_ERROR_CHECK
//#define ID18_HASH_COMPILE_ERROR_CHECK
//#define ID26_HASH_COMPILE_ERROR_CHECK
